### ISSUE TITLE
Doesn't work for version 8.2

### ISSUE THREAD

**Issue by dipomajek** [Kentico/DisqusThread#1]
Unable to import the web part for version 8.2

Error during temporary files creation. Original exception: [ImportProvider.LoadObjects]: Cannot import data from newer version '9.0' to current version '8.2'.

**Comment by petrsvihlik** [comment]
@dipolediamond thanks. i've added export packages for the other versions

https://github.com/Kentico/DisqusThread/releases/tag/1.1
